// This file is generated by the FlutterFire CLI.
// Run the following commands to regenerate it with your Firebase project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then this stub prevents compile errors. Replace the entire file
// with the CLI-generated output before running the app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate the options.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6qkOHbicQc5ndK9ruDVqK6ksreOMv4s',
    appId: '1:303809461952:android:efbc9a031bd6d2889bf725',
    messagingSenderId: '303809461952',
    projectId: 'localdelivery-2ca48',
    storageBucket: 'localdelivery-2ca48.firebasestorage.app',
  );

  // TODO: Register a separate iOS app in the Firebase console for the admin
  // app and run `flutterfire configure` to replace these placeholder values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrqBXVX8mQ7nae4neWXfT4lPAJa_DWrQ',
    appId: '1:303809461952:ios:3f93cc90381219b29bf725',
    messagingSenderId: '303809461952',
    projectId: 'localdelivery-2ca48',
    storageBucket: 'localdelivery-2ca48.firebasestorage.app',
    iosBundleId: 'com.localdelivery.localDeliveryAdmin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtIwuqqMRDIMIr9hX16nwIJWuxpjHzlE0',
    appId: '1:303809461952:web:1922d46ad3a7b7429bf725',
    messagingSenderId: '303809461952',
    projectId: 'localdelivery-2ca48',
    authDomain: 'localdelivery-2ca48.firebaseapp.com',
    storageBucket: 'localdelivery-2ca48.firebasestorage.app',
    measurementId: 'G-G8L8P588Q6',
  );
}
